sonar.projectKey=my-org_my-repo-key
sonar.projectName=My Application
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/*.spec.js

# Language encoding
sonar.sourceEncoding=UTF-8
sonar.organization=herise-ops
